//! execute_graph.rs
//!
//! Calls the Encrypt program's `execute_graph` instruction via CPI.
//!
//! HOW execute_graph WORKS (from the Encrypt pre-alpha docs):
//!
//!   The `EncryptCpi` trait (from encrypt-anchor) exposes `execute_graph`.
//!   You pass:
//!     - The graph_id: a [u8; 32] constant generated by the #[encrypt_fn] macro
//!     - Input ciphertext account Pubkeys (the EUint64/EBool inputs in order)
//!     - An output ciphertext account (created by the Encrypt program)
//!
//!   The Encrypt program:
//!     1. Validates inputs
//!     2. Records the graph execution and emits a GraphExecutionRequested event
//!     3. The off-chain executor picks up the event, evaluates the FHE graph,
//!        and calls commit_ciphertext to write the output back on-chain
//!
//!   Your program polls the output ciphertext account until it's populated,
//!   then either uses it as input to another graph, or calls request_decryption.

use anchor_lang::prelude::*;
use encrypt_anchor::EncryptCpi;
use crate::{
    errors::LendingError,
    fhe::graphs::{
        CHECK_COLLATERAL_GRAPH_ID,
        APPLY_REPAYMENT_GRAPH_ID,
        IS_LIQUIDATABLE_GRAPH_ID,
    },
    state::{GraphKind, GraphRecord, LendingPosition, Market, PositionStatus},
};

pub fn handler(ctx: Context<ExecuteGraph>, kind: GraphKind) -> Result<()> {
    let position = &mut ctx.accounts.position;
    let market   = &ctx.accounts.market;
    let clock    = Clock::get()?;

    // ── Validate position state for the requested graph ───────────────────
    match &kind {
        GraphKind::CollateralCheck => {
            require!(
                position.status == PositionStatus::PendingCheck,
                LendingError::WrongState,
            );
        }
        GraphKind::Repayment => {
            require!(
                position.status == PositionStatus::Active,
                LendingError::WrongState,
            );
            position.status = PositionStatus::Repaying;
        }
        GraphKind::LiquidationCheck => {
            require!(
                position.status == PositionStatus::Active,
                LendingError::WrongState,
            );
        }
    }

    // ── Build input list for this graph ───────────────────────────────────
    //
    // Inputs must be in the same order as the #[encrypt_fn] function parameters.
    // The graph_id ties this call to the specific compiled function.

    let (graph_id, inputs) = match &kind {
        GraphKind::CollateralCheck => (
            CHECK_COLLATERAL_GRAPH_ID,
            // check_collateral(collateral: EUint64, loan: EUint64)
            vec![position.collateral_ct, position.loan_ct],
        ),
        GraphKind::Repayment => (
            APPLY_REPAYMENT_GRAPH_ID,
            // apply_repayment(outstanding: EUint64, repayment: EUint64)
            // The repayment ciphertext is supplied by the borrower via the extra account
            vec![
                position.outstanding_ct,
                ctx.accounts.extra_ct.key(), // repayment amount ciphertext
            ],
        ),
        GraphKind::LiquidationCheck => (
            IS_LIQUIDATABLE_GRAPH_ID,
            // is_liquidatable(collateral_value, outstanding, min_ratio_bps)
            // min_ratio_bps is passed as a public constant graph parameter,
            // NOT as a ciphertext. It's encoded in the graph call params.
            vec![position.collateral_ct, position.outstanding_ct],
        ),
    };

    // ── CPI: execute_graph on the Encrypt program ─────────────────────────
    //
    // encrypt_anchor::EncryptCpi wraps the execute_graph instruction.
    // The output_ct account will be populated by the Encrypt executor
    // after it evaluates the FHE graph off-chain.
    ctx.accounts.encrypt_cpi.execute_graph(
        &ctx.accounts.encrypt_program.to_account_info(),
        &ctx.accounts.output_ct.to_account_info(),
        &ctx.accounts.payer.to_account_info(),
        &ctx.accounts.system_program.to_account_info(),
        graph_id,
        inputs,
    )?;

    // ── Update position with the output ciphertext reference ──────────────
    match &kind {
        GraphKind::CollateralCheck => {
            position.collateral_check_output_ct = ctx.accounts.output_ct.key();
            position.collateral_check_slot      = clock.slot;
            position.status = PositionStatus::PendingDecryption;
        }
        GraphKind::Repayment => {
            // The repayment graph returns (remaining: EUint64, fully_repaid: EBool)
            // The output_ct is the first output (remaining balance).
            // A second output account is needed for the bool — handled in finalize.rs.
            position.outstanding_ct = ctx.accounts.output_ct.key();
        }
        GraphKind::LiquidationCheck => {
            position.liquidation_check_output_ct = ctx.accounts.output_ct.key();
        }
    }

    // ── Record the graph execution for off-chain polling ──────────────────
    let record       = &mut ctx.accounts.graph_record;
    record.position  = position.key();
    record.graph_kind = kind;
    record.output_ct = ctx.accounts.output_ct.key();
    record.executed_at_slot = clock.slot;
    record.bump      = ctx.bumps.graph_record;

    emit!(GraphExecuted {
        position:       position.key(),
        output_ct:      ctx.accounts.output_ct.key(),
        executed_slot:  clock.slot,
    });
    Ok(())
}

#[derive(Accounts)]
#[instruction(kind: GraphKind)]
pub struct ExecuteGraph<'info> {
    #[account(
        seeds = [
            b"market",
            market.collateral_mint.as_ref(),
            market.borrow_mint.as_ref(),
        ],
        bump = market.bump,
    )]
    pub market: Account<'info, Market>,

    #[account(
        mut,
        has_one = market,
        seeds = [
            b"position",
            market.key().as_ref(),
            position.borrower.as_ref(),
            &position.index.to_le_bytes(),
        ],
        bump = position.bump,
    )]
    pub position: Account<'info, LendingPosition>,

    /// GraphRecord PDA — seeded by position + current slot for uniqueness
    #[account(
        init,
        payer = payer,
        space = GraphRecord::LEN,
        seeds = [
            b"graph",
            position.key().as_ref(),
            &Clock::get().unwrap().slot.to_le_bytes(),
        ],
        bump,
    )]
    pub graph_record: Account<'info, GraphRecord>,

    /// CHECK: Output ciphertext account. Encrypt initialises this during
    /// execute_graph. We pass it as a mutable writable account.
    #[account(mut)]
    pub output_ct: UncheckedAccount<'info>,

    /// CHECK: Extra ciphertext account (only used for Repayment graph —
    /// the repayment amount ciphertext submitted by the borrower).
    /// Pass SystemProgram id for other graph kinds.
    pub extra_ct: UncheckedAccount<'info>,

    /// EncryptCpi account bundle from encrypt-anchor.
    /// This wraps the accounts needed for the execute_graph CPI.
    pub encrypt_cpi: EncryptCpi<'info>,

    /// CHECK: The Encrypt program — verified against market.encrypt_program
    #[account(address = market.encrypt_program @ LendingError::BadCiphertextOwner)]
    pub encrypt_program: UncheckedAccount<'info>,

    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[event]
pub struct GraphExecuted {
    pub position:      Pubkey,
    pub output_ct:     Pubkey,
    pub executed_slot: u64,
}
